name: been_there
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.6.0
  flutter_riverpod: ^2.6.1
  cloud_firestore: ^5.4.4
  go_router: ^14.3.0
  fluttertoast: ^8.2.8
  sign_in_with_apple: ^6.1.3
  firebase_auth: ^5.3.1
  google_sign_in: ^6.2.1
  mapbox_maps_flutter: ^2.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
