// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAqQs0ppT2KxEkgrALgm1VkFunWW29-HBc',
    appId: '1:937513767406:android:0106b5b93a4ceef0d7beff',
    messagingSenderId: '937513767406',
    projectId: 'beenthere-f863f',
    storageBucket: 'beenthere-f863f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-Vm-9yfg_S5x9RnB1xYfcTEUFIgaMUj0',
    appId: '1:937513767406:ios:0a46b75255ebb044d7beff',
    messagingSenderId: '937513767406',
    projectId: 'beenthere-f863f',
    storageBucket: 'beenthere-f863f.appspot.com',
    androidClientId: '937513767406-4gi3gqoi75pmmivl62h1q3femi0rh6ab.apps.googleusercontent.com',
    iosClientId: '937513767406-eej8mh3q0092ovemata699vcs58okn3h.apps.googleusercontent.com',
    iosBundleId: 'com.example.beenThere',
  );
}
